### ISSUE TITLE
Integration with styled-components

### ISSUE THREAD

**Issue by AbdallahBedir** [sixfootsixdesigns/React-Library-Boilerplate#25]
Unfortunately, It doesn't work with any component that imports `styled-components`

**Comment by AbdallahBedir** [comment]
```
react.development.js:1438 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1438:1)
    at useDebugValue (react.development.js:1509:1)
    at styled-components.browser.esm.js:731:1
    at O (styled-components.browser.esm.js:769:1)
    at renderWithHooks (react-dom.development.js:16187:1)
    at updateForwardRef (react-dom.development.js:19961:1)
```

**Comment by AbdallahBedir** [comment]
It was because of `npm link` https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react
